create table cart (
	cart_id INT NOT NULL UNIQUE,
    FOREIGN KEY (cart_id) REFERENCES customer (customer_id)
    ON DELETE CASCADE,
	total_cost DECIMAL(10, 2) NOT NULL,
	description_info TEXT NOT NULL
);

insert into cart (cart_id, total_cost, description_info) values 
 (1, 0,  'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl'),
 (2, 0,  'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla'),
 (3, 0, 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel'),
 (4, 0, 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum'),
 (5, 0, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi'),
 (6, 0, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit'),
 (7, 0, 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend'),
 (8, 0, 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet'),
 (9, 0, 'aliquam convallis nunc proin at turpis a pede posuere nonummy integer non'),
 (10, 0, 'quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis'),
 (11, 0, 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam'),
 (12, 0, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel'),
 (13, 0, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla'),
 (14, 0, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla'),
 (15, 0, 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi'),
 (16, 0, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna'),
 (17, 0, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis'),
 (18, 0, 'ligula vehicula consequat morbi a ipsum integer a nibh in'),
 (19, 0, 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
 (20, 0, 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla'),
 (21, 0, 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris'),
 (22, 0, 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci'),
 (23, 0, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at'),
 (24, 0, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis'),
 (25, 0, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est'),
 (26, 0, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in'),
 (27, 0, 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla'),
 (28, 0, 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at'),
 (29, 0, 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante'),
 (30, 0, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient'),
 (31, 0, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget'),
 (32, 0, 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit'),
 (33, 0, 'nibh fusce lacus purus aliquet at feugiat non pretium quis'),
 (34, 0, 'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit'),
 (35, 0, 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id'),
 (36, 0, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in'),
 (37, 0, 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac'),
 (38, 0, 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec'),
 (39, 0, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta'),
 (40, 0, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in'),
 (41, 0, 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam'),
 (42, 0, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a'),
 (43, 0, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi'),
 (44, 0, 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo'),
 (45, 0, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent'),
 (46, 0, 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede'),
 (47, 0, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices'),
 (48, 0, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient'),
 (49, 0, 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante'),
 (50, 0, 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam'),
 (51, 0, 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum'),
 (52, 0, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
 (53, 0, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet'),
 (54, 0, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing'),
 (55, 0, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus'),
 (56, 0, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque'),
 (57, 0, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non'),
 (58, 0, 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum'),
 (59, 0, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst'),
 (60, 0, 'posuere cubilia curae nulla dapibus dolor vel est donec odio'),
 (61, 0, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat'),
 (62, 0, 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia'),
 (63, 0, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien'),
 (64, 0, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis'),
 (65, 0, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc'),
 (66, 0, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat'),
 (67, 0, 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis'),
 (68, 0, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate'),
 (69, 0, 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit'),
 (70, 0, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae'),
 (71, 0, 'sapien a libero nam dui proin leo odio porttitor id consequat'),
 (72, 0, 'nulla elit ac nulla sed vel enim sit amet nunc viverra'),
 (73, 0, 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam'),
 (74, 0, 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu'),
 (75, 0, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien'),
 (76, 0, 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper'),
 (77, 0, 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio'),
 (78, 0, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
 (79, 0, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim'),
 (80, 0, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique'),
 (81, 0, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu'),
 (82, 0, 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum'),
 (83, 0, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus'),
 (84, 0, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra'),
 (85, 0, 'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus'),
 (86, 0, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada'),
 (87, 0, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec'),
 (88, 0, 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus'),
 (89, 0, 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae'),
 (90, 0, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et'),
 (91, 0, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante'),
 (92, 0, 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus'),
 (93, 0, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in'),
 (94, 0, 'risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl'),
 (95, 0, 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in'),
 (96, 0, 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla'),
 (97, 0, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
 (98, 0, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam'),
 (99, 0, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus'),
 (100, 0, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
 